trigger:
  branches:
    include:
    - master
  paths:
    include:
    - 'src'

pool:
  vmImage: 'ubuntu-latest'

variables:
   major: 1
   minor: 0
   patch: 0

name: $(major).$(minor).$(patch).$(rev:.rrr)

steps:
- task: CmdLine@2
  inputs:
    script: 'cd src && ls'


